config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages
  get '/activity', to: "messages#activity"

  get '/login', to: "users#new"
  post '/login', to: "users#create"
  delete '/logout', to: "users#destroy"
 
  mount ActionCable.server => '/cable'
end

app/models/.#base.rb
arthur@Arthurs-MacBook-Pro.local.79740

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
class Base
  def initialize(message, dialect)
    @message = message
    @dialect = dialect
  end

  def base_uri
    API[:base_uri]
  end

  def translate
    parse response
  end

  def response
    RestClient::Request.execute(method: :post,
                                url: base_uri,
                                payload: {d: @dialect,
                                          w: @message})
  end

  def parse(result)
    text = HtmlParser.new(result.body)
    text.search("blockquote")
  end
end

app/models/binary.rb
class Binary < Base
end

app/models/html_parser.rb
class HtmlParser
  def initialize(text)
    @text = text
  end

  def search(tag)
    result = @text.scan(/<#{tag}>(.*)<\/#{tag}>/m).flatten.first
    sanitize(result)
  end

  def sanitize(text)
    ActionView::Base.full_sanitizer.sanitize(text).strip
  end
end

app/models/message.rb
class Message < ApplicationRecord
  scope :latest, -> { order(:created_at).last(100) }

  def translate
    dispatch.translate
  end

  def dispatch
    clazz ||= class_eval(dialect.to_s.capitalize)
    clazz.new(text, dialect)
  end

  def scanned_mentions
    text.scan(/@(#{User::USERNAME_REGEX})/).flatten
  end

  def mentions
    scanned_mentions.map do |username|
      UserActivity.active(username)
    end.compact
  end
end

app/models/user.rb
class User
  attr_accessor :username, :dialect

  DIALECTS = %w(yoda valley binary).freeze
  USERNAME_REGEX = /\w+/

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  validates :username, presence: true,
            format: { with: /\A#{USERNAME_REGEX}\z/i },
            length: { maximum: 15 }
  validates :dialect, :presence => true
  validates_inclusion_of :dialect, in: DIALECTS, allow_nil: false
  validate :username_already_taken

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def username_already_taken
    unless UserActivity.active(self.username).blank?
      errors.add(:username, "#{self.username} has already been taken")
    end
  end
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
  belongs_to :user

  scope :active, -> (username) do
    where(username: username, status: 'activate')
  end
  scope :online, -> { where(status: 'activate') }
end

app/models/valley.rb
class Valley < Base
end

app/models/yoda.rb
class Yoda < Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include ApplicationHelper

  def logged_in?
    !!current_user
  end

  def redirect_logged_in?
    redirect_to messages_path and return if logged_in?
  end

  protected

  def authenticate_user!
    redirect_to login_path and return unless logged_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :messages, only: [:index]

  def index
    @message = Message.new
  end

  def create
    message = Message.new(message_params)
    message.dialect = current_dialect
    message.username = current_user
    message.translated = message.translate
    if message.save
      publish message
    end
  end

  def activity
    register_user
  end

  private
    def message_params
      params.require(:message).permit(:text, :username, :status)
    end

    def messages
      @messages = Message.latest
      @users = UserActivity.where(status: 'activate')
    end

    def publish(message)
      ActionCable.server.broadcast('messages',
                                   message: message.translated,
                                   dialect: message.dialect,
                                   mentions: message.mentions,
                                   username: message.username)
      head :ok
    end

    def register_user
      activity = UserActivity.find_or_initialize_by(username: current_user)
      activity.dialect = current_dialect
      activity.status = message_params[:status]
      if activity.save
        ActionCable.server.broadcast('users', username: current_user,
                                     dialect: current_dialect,
                                     status: message_params[:status])
      end
      head :no_content
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:destroy]
  before_action :redirect_logged_in?, only: [:new]
  layout 'user'

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      create_session
      redirect_to messages_path, success: 'User was successfully logged in.'
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  def create_session
    if @user.valid?
      session[:username] = @user.username
      session[:dialect] = @user.dialect
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :dialect, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= session[:username] if session[:username]
  end

  def current_dialect
    @current_dialect ||= session[:dialect] if session[:dialect]
  end
end

app/helpers/messages_helper.rb
module MessagesHelper

  def chat_side(username)
    (username == current_user) ? 'left' : 'right'
  end

  def time(created_at)
    created_at.strftime("%d/%b/%Y %H:%M:%S")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_flash_messages.html.erb
<%  if alert %>
<div class="alert alert-danger">
  <%= alert %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>TwistedChat</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar navbar-toggleable-md navbar-inverse bg-primary mb-4">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">
                <img src="<%= asset_path 'logo.png' %>" width="30" height="30" class="d-inline-block align-top" alt="">
                TwistedChat</a>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <%= link_to 'Log out', logout_path, :method=>'delete', class: 'nav-item nav-link' %>
                </div>
            </div>

        </nav>
        <div class="container">
            <%= render partial: 'layouts/flash_messages'%>
            <%= yield %>
        </div>
    </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
    <head>
	<title>TwistedChat</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
    </head>
    <body class="login">
	<div class="container">
	    <%= render partial: 'layouts/flash_messages'%>
	    <%= yield %>
	</div>
    </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="row">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header title">Chat</div>
            <div class="card-block">
                <ul id="messages" class="messages">
                    <% @messages.each do |message| %>
                        <li class="message <%= chat_side(message.username) -%>">
                            <div class="img-thumbnail avatar <%= message.dialect -%>"></div>
                            <div class="text_wrapper">
                                <span class="username"><%= message.username %></span>
                                <span class="time float-right"><%= time(message.created_at) %></span>
                                <div class="text">
                                    <%= message.translated -%>
                                </div'
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
            <div class="card-footer">
                <%=form_for @message, remote: true, authenticity_token: true do |f|%>
                        <div class="input-group">
                            <%= f.text_area :text, class: "form-control", cols: 40, rows: 3, data: {textarea: "message"}%>
                            <div class="input-group-btn">
                                <%= f.submit "Send", class: "btn btn-primary", data: {send: "message"}%>

                                <%= f.hidden_field :username, value: current_user  %>
                            </div>
                        </div>
                        <span class="help-block">You can mention an user by typing @ plus their username</span>
                <%end%>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="card-header title">Active users</div>
            <div class="card-block p-0">
                <ul class="list-group" id="users">
                    <% @users.each do |activity| %>
                        <li class="list-group-item" id="user-<%= activity.username -%>">
                            <div class="row">
                                <div class="col-md-2 img-thumbnail avatar <%= activity.dialect -%>"></div>
                                <div class="col p-2">
                                    <span class="name"><%= activity.username -%></span><br/>
                                </div>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<p>
  <strong>Username:</strong>
  <%= @message.username %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for(User.new, url: login_path, authenticity_token: true, html: {class: 'form-signin'}) do |f| %>
    <h2 class="form-signin-heading">Authentication</h2>
    <div class="input-group">
        <div class="input-group-addon">@</div>
        <%= f.text_field :username, class: "form-control", value: @user.username -%>
    </div>
    <div class="form-group">
        <%= f.select :dialect,
        User::DIALECTS.map { |value| [ value.capitalize, value ] },
        {}, {class: "form-control"} %>
    </div>
    <%= f.submit "Enter", class: "btn btn-large btn-primary btn-block" %>

<% end %>